/**
 * Precedent Court Cases, Judgments & Demo Presets Seed Data
 * Matches Case Table & Judgment Table in context/backend.md
 */

const courts = require('./courts.seed');
const provisions = require('./provisions.seed');

const precedents = [
  {
    id: "case_001",
    case_id: "PREC-001",
    title: "State of Tamil Nadu vs. Ramesh @ Suresh Kumar",
    citation: "2021 SCC OnLine Mad 4521",
    court_id: 2,
    courtId: "court_002",
    courtName: "Madras High Court",
    court_name: "Madras High Court",
    year: 2021,
    location: "T. Nagar, Chennai, Tamil Nadu",
    offence: "Armed Robbery / Dacoity",
    legal_provisions: ["IPC Section 392", "IPC Section 397", "BNS Section 309", "BNS Section 311"],
    legalProvisions: ["IPC Section 392", "IPC Section 397", "BNS Section 309", "BNS Section 311"],
    weapon: "Butcher Knife / Dagger",
    victim: "Jewellery Showroom Owner & Cashier",
    circumstances: "Assailant entered jewellery store during closing hours brandishing 12-inch butcher knife. Stole 450g gold ornaments after inflicting minor cut to staff.",
    description: "Robbery at jewellery showroom in T. Nagar. Large knife used to intimidate staff and smash glass counters. Mandatory 7-year minimum sentence under Sec 397 IPC affirmed.",
    case_description: "Robbery at jewellery showroom in T. Nagar. Large knife used to intimidate staff and smash glass counters. Mandatory 7-year minimum sentence under Sec 397 IPC affirmed.",
    is_precedent: true,
    judgment: {
      judgment_id: 1,
      case_id: "PREC-001",
      facts: "Two assailants entered Sri Mahalaxmi Jewellers in T. Nagar. Accused 1 held a 12-inch butcher knife at the proprietor's throat while Accused 2 smashed display showcases. Total stolen jewellery weighed 450 grams. Weapon was recovered within 48 hours.",
      case_facts: "Two assailants entered Sri Mahalaxmi Jewellers in T. Nagar. Accused 1 held a 12-inch butcher knife at the proprietor's throat while Accused 2 smashed display showcases. Total stolen jewellery weighed 450 grams.",
      legalIssues: "1. Does brandishing a weapon during a shop robbery attract mandatory 7-year minimum sentence under Section 397 IPC?\n2. Presumption of guilt under Section 114(a) Evidence Act on recovery within 48 hours.",
      legal_issues: "1. Does brandishing a weapon during a shop robbery attract mandatory 7-year minimum sentence under Section 397 IPC?\n2. Presumption of guilt under Section 114(a) Evidence Act on recovery within 48 hours.",
      arguments: "Prosecution: Weapon was deadly and used to overawe staff.\nDefence: Accused was not the person wielding the knife and suffered no grievous harm.",
      courtReasoning: "Section 397 does not require grievous hurt if a deadly weapon is used to create terror and facilitate robbery (citing Phool Kumar v. Delhi Admn.). Recovery within 48 hours establishes robust presumption of guilt.",
      court_reasoning: "Section 397 does not require grievous hurt if a deadly weapon is used to create terror and facilitate robbery (citing Phool Kumar v. Delhi Admn.). Recovery within 48 hours establishes robust presumption of guilt.",
      finalDecision: "Conviction under IPC Section 392 r/w 397 upheld. 7 years rigorous imprisonment.",
      final_decision: "Conviction under IPC Section 392 r/w 397 upheld. 7 years rigorous imprisonment.",
      citations: "Phool Kumar v. Delhi Admn. (1975) 1 SCC 797; Dilawar Singh v. State of Delhi (2007) 12 SCC 641."
    }
  },
  {
    id: "case_002",
    case_id: "PREC-002",
    title: "Muthuvel vs. Inspector of Police, Flower Bazaar PS",
    citation: "2019 (3) MWN (Cr.) 182 (Mad.)",
    court_id: 2,
    courtId: "court_002",
    courtName: "Madras High Court",
    court_name: "Madras High Court",
    year: 2019,
    location: "George Town, Chennai, Tamil Nadu",
    offence: "Robbery with Deadly Weapon",
    legal_provisions: ["IPC Section 397", "IPC Section 392"],
    legalProvisions: ["IPC Section 397", "IPC Section 392"],
    weapon: "Folding Knife / Sharp Weapon",
    victim: "Gold Merchant / Trader",
    circumstances: "Assailant intercepted a gold bullion dealer while carrying jewellery samples in a commercial market lane and stole gold chains after inflicting a slash.",
    description: "Merchant intercepted in bazaar lane by motorcycle-borne assailant wielding knife. High Court examined Section 397 minimum sentence applicability.",
    case_description: "Merchant intercepted in bazaar lane by motorcycle-borne assailant wielding knife. High Court examined Section 397 minimum sentence applicability.",
    is_precedent: true,
    judgment: {
      judgment_id: 2,
      case_id: "PREC-002",
      facts: "Wholesale gold merchant intercepted in Flower Bazaar by motorcycle assailant wielding sharp folding knife. Bag with 350g gold ornaments snatched.",
      case_facts: "Wholesale gold merchant intercepted in Flower Bazaar by motorcycle assailant wielding sharp folding knife. Bag with 350g gold ornaments snatched.",
      legalIssues: "Whether 4-inch folding knife qualifies as deadly weapon under Section 397 IPC.",
      legal_issues: "Whether 4-inch folding knife qualifies as deadly weapon under Section 397 IPC.",
      arguments: "Prosecution: Sharp knife aimed at upper torso is inherently deadly.\nDefence: Complainant was a stranger and absence of TIP rendered dock identification doubtful.",
      courtReasoning: "A sharp blade targeted at upper torso is capable of causing fatality. Dock identification held reliable due to clear daylight occurrence.",
      court_reasoning: "A sharp blade targeted at upper torso is capable of causing fatality. Dock identification held reliable due to clear daylight occurrence.",
      finalDecision: "Conviction under Sec 392/397 confirmed. 7 years RI.",
      final_decision: "Conviction under Sec 392/397 confirmed. 7 years RI.",
      citations: "State of Maharashtra v. Vinayak (1997) CriLJ 3988."
    }
  },
  {
    id: "case_003",
    case_id: "PREC-003",
    title: "K. Selvam & Anr. vs. State by Sub-Inspector, Coimbatore",
    citation: "2022 SCC OnLine Mad 1890",
    court_id: 3,
    courtId: "court_003",
    courtName: "Madras High Court (Madurai Bench)",
    court_name: "Madras High Court (Madurai Bench)",
    year: 2022,
    location: "Gandhipuram, Coimbatore, Tamil Nadu",
    offence: "Attempted Robbery and Hurt",
    legal_provisions: ["IPC Section 392", "IPC Section 394", "IPC Section 307"],
    legalProvisions: ["IPC Section 392", "IPC Section 394", "IPC Section 307"],
    weapon: "Iron Rod & Pocket Knife",
    victim: "Pawn Broker & Store Clerk",
    circumstances: "Accused posed as customers in a pawn broker store, attempted to overpower manager with iron rod and knife. Store alarm triggered.",
    description: "Attempted armed robbery at pawn shop where perpetrators used iron rod and knife. High Court examined Section 397 applicability for attempts.",
    case_description: "Attempted armed robbery at pawn shop where perpetrators used iron rod and knife. High Court examined Section 397 applicability for attempts.",
    is_precedent: true,
    judgment: {
      judgment_id: 3,
      case_id: "PREC-003",
      facts: "Perpetrators posed as borrowers pledging gold in a pawn shop. One produced an iron rod while the other pulled a knife. Clerk pressed panic alarm.",
      case_facts: "Perpetrators posed as borrowers pledging gold in a pawn shop. One produced an iron rod while the other pulled a knife. Clerk pressed panic alarm.",
      legalIssues: "Whether conviction under Section 397 is sustainable when the attempt was aborted before full looting was accomplished.",
      legal_issues: "Whether conviction under Section 397 is sustainable when the attempt was aborted before full looting was accomplished.",
      arguments: "Defence argued attempt was aborted. Prosecution argued Section 397 explicitly covers attempts with deadly weapons.",
      courtReasoning: "The wording of Section 397 explicitly includes attempt to commit robbery. Incomplete robbery does not exempt perpetrator when deadly weapon was brandished.",
      court_reasoning: "The wording of Section 397 explicitly includes attempt to commit robbery. Incomplete robbery does not exempt perpetrator when deadly weapon was brandished.",
      finalDecision: "Convicted under Section 392 read with Section 397 IPC. 7 years RI.",
      final_decision: "Convicted under Section 392 read with Section 397 IPC. 7 years RI.",
      citations: "Shravan v. State of Rajasthan (1977) CriLJ 1638."
    }
  },
  {
    id: "case_004",
    case_id: "PREC-004",
    title: "Vinod @ Pappu vs. State of Maharashtra",
    citation: "2020 (4) BomCR (Cri) 310",
    court_id: 4,
    courtId: "court_004",
    courtName: "Bombay High Court",
    court_name: "Bombay High Court",
    year: 2020,
    location: "Zaveri Bazaar, Mumbai, Maharashtra",
    offence: "Armed Robbery in Commercial Establishment",
    legal_provisions: ["IPC Section 392", "IPC Section 397", "BNS Section 311"],
    legalProvisions: ["IPC Section 392", "IPC Section 397", "BNS Section 311"],
    weapon: "Rampuri Knife",
    victim: "Jeweller & Security Guard",
    circumstances: "Three assailants barged into jewellery showroom in Zaveri Bazaar, subdued guard with knife threat, broke showcase cabinets, and decamped with diamond rings.",
    description: "Daylight robbery at jewellery store in Zaveri Bazaar. Court analyzed Section 34 vs individual liability under Section 397 for co-accused who did not carry weapons.",
    case_description: "Daylight robbery at jewellery store in Zaveri Bazaar. Court analyzed Section 34 vs individual liability under Section 397 for co-accused who did not carry weapons.",
    is_precedent: true,
    judgment: {
      judgment_id: 4,
      case_id: "PREC-004",
      facts: "Three masked men raided jewellery shop. Knife was held by Accused 1; Accused 2 collected jewels; Accused 3 stood guard.",
      case_facts: "Three masked men raided jewellery shop. Knife was held by Accused 1; Accused 2 collected jewels; Accused 3 stood guard.",
      legalIssues: "Can co-accused who did not hold weapons be convicted under Section 397 via Section 34?",
      legal_issues: "Can co-accused who did not hold weapons be convicted under Section 397 via Section 34?",
      arguments: "Appellant contended he only collected ornaments and never possessed any weapon.",
      courtReasoning: "Section 397 is an individual liability provision. Accomplices who did not physically carry weapon are liable under Sec 392/34, not Sec 397.",
      court_reasoning: "Section 397 is an individual liability provision. Accomplices who did not physically carry weapon are liable under Sec 392/34, not Sec 397.",
      finalDecision: "Knife wielder given 7 years Sec 397. Co-accused sentence reduced to 4 years Sec 392/34.",
      final_decision: "Knife wielder given 7 years Sec 397. Co-accused sentence reduced to 4 years Sec 392/34.",
      citations: "Dilawar Singh v. State of Delhi (2007) 12 SCC 641; Ashfaq v. State (2004) 3 SCC 416."
    }
  },
  {
    id: "case_005",
    case_id: "PREC-005",
    title: "Sanjay Kumar vs. State (NCT of Delhi)",
    citation: "2023 DHC 3412",
    court_id: 5,
    courtId: "court_005",
    courtName: "Delhi High Court",
    court_name: "Delhi High Court",
    year: 2023,
    location: "Karol Bagh, New Delhi",
    offence: "Robbery with Common Intention",
    legal_provisions: ["IPC Section 392", "IPC Section 34", "IPC Section 397"],
    legalProvisions: ["IPC Section 392", "IPC Section 34", "IPC Section 397"],
    weapon: "Kitchen Knife & Toy Pistol",
    victim: "Jewellery Retailer",
    circumstances: "Two accused entered jewellery store posing as buyers seeking wedding gold sets. One brandished kitchen knife while other had fake gun.",
    description: "Posing as customers in Karol Bagh jewellery outlet, accused brandished knife and fake firearm. Court examined whether toy pistol is deadly weapon.",
    case_description: "Posing as customers in Karol Bagh jewellery outlet, accused brandished knife and fake firearm. Court examined whether toy pistol is deadly weapon.",
    is_precedent: true,
    judgment: {
      judgment_id: 5,
      case_id: "PREC-005",
      facts: "Two men entered Karol Bagh jewellery store. Accused 1 pulled out 10-inch kitchen knife; Accused 2 produced toy pistol.",
      case_facts: "Two men entered Karol Bagh jewellery store. Accused 1 pulled out 10-inch kitchen knife; Accused 2 produced toy pistol.",
      legalIssues: "Does a replica pistol qualify as deadly weapon under Section 397 IPC?",
      legal_issues: "Does a replica pistol qualify as deadly weapon under Section 397 IPC?",
      arguments: "Defence argued toy pistol is not deadly. State argued victim perceived immediate mortal danger.",
      courtReasoning: "A toy pistol cannot inflict grievous hurt or death and is not deadly under Sec 397. 10-inch pointed kitchen knife is a deadly weapon.",
      court_reasoning: "A toy pistol cannot inflict grievous hurt or death and is not deadly under Sec 397. 10-inch pointed kitchen knife is a deadly weapon.",
      finalDecision: "Knife wielder convicted under Sec 397 (7 years RI). Toy pistol holder convicted under Sec 392 (3 years RI).",
      final_decision: "Knife wielder convicted under Sec 397 (7 years RI). Toy pistol holder convicted under Sec 392 (3 years RI).",
      citations: "State of Maharashtra v. Vinayak (1997) CriLJ 3988."
    }
  },
  {
    id: "case_006",
    case_id: "PREC-006",
    title: "Rajesh Sharma vs. State of Karnataka & Anr.",
    citation: "2023 SCC OnLine Kar 567",
    court_id: 6,
    courtId: "court_006",
    courtName: "Karnataka High Court",
    court_name: "Karnataka High Court",
    year: 2023,
    location: "Electronic City, Bengaluru, Karnataka",
    offence: "Online Financial Fraud & Cheating",
    legal_provisions: ["IPC Section 420", "BNS Section 318(4)", "IT Act Section 66D", "CrPC Section 439"],
    legalProvisions: ["IPC Section 420", "BNS Section 318(4)", "IT Act Section 66D", "CrPC Section 439"],
    weapon: "None (Digital / Cyber Fraud)",
    victim: "IT Professional & Public Investors",
    circumstances: "Accused operated a fake crypto-investment portal, siphoned funds via multi-layer mule accounts.",
    description: "Cyber investment fraud where victims were induced via Telegram groups to invest in a fictitious portal. Regular bail granted under Section 439 CrPC.",
    case_description: "Cyber investment fraud where victims were induced via Telegram groups to invest in a fictitious portal. Regular bail granted under Section 439 CrPC.",
    is_precedent: true,
    judgment: {
      judgment_id: 6,
      case_id: "PREC-006",
      facts: "Petitioner accused of participating in multi-crore investment scam. Charge sheet filed after 90 days in custody.",
      case_facts: "Petitioner accused of participating in multi-crore investment scam. Charge sheet filed after 90 days in custody.",
      legalIssues: "Bail in economic offences during ongoing money trail investigation.",
      legal_issues: "Bail in economic offences during ongoing money trail investigation.",
      arguments: "Petitioner: Investigation completed and charge sheet filed.\nState: Multi-state syndicate risk.",
      courtReasoning: "Prolonged pre-trial detention without trial commencement violates Article 21 personal liberty.",
      court_reasoning: "Prolonged pre-trial detention without trial commencement violates Article 21 personal liberty.",
      finalDecision: "Bail granted on Rs 25 Lakhs indemnity bond and passport deposit.",
      final_decision: "Bail granted on Rs 25 Lakhs indemnity bond and passport deposit.",
      citations: "Sanjay Chandra v. CBI (2012) 1 SCC 40; P. Chidambaram v. CBI (2020) 13 SCC 337."
    }
  },
  {
    id: "case_007",
    case_id: "PREC-007",
    title: "Arnesh Kumar vs. State of Bihar",
    citation: "(2014) 8 SCC 273",
    court_id: 1,
    courtId: "court_001",
    courtName: "Supreme Court of India",
    court_name: "Supreme Court of India",
    year: 2014,
    location: "Patna, Bihar",
    offence: "Bail & Arrest Guidelines for offences < 7 years",
    legal_provisions: ["CrPC Section 41", "CrPC Section 438", "BNSS Section 35", "Constitution Article 21"],
    legalProvisions: ["CrPC Section 41", "CrPC Section 438", "BNSS Section 35", "Constitution Article 21"],
    weapon: "None",
    victim: "Accused in bailable / minor offences",
    circumstances: "Landmark judgment establishing strict checklist guidelines to prevent unnecessary arrests by police in offences punishable up to 7 years.",
    description: "Supreme Court guidelines directing magistrates and police not to arrest automatically without Section 41A notice.",
    case_description: "Supreme Court guidelines directing magistrates and police not to arrest automatically without Section 41A notice.",
    is_precedent: true,
    judgment: {
      judgment_id: 7,
      case_id: "PREC-007",
      facts: "Appellant sought anticipatory bail highlighting arbitrary police arrest powers in matrimonial disputes.",
      case_facts: "Appellant sought anticipatory bail highlighting arbitrary police arrest powers in matrimonial disputes.",
      legalIssues: "Mandatory compliance of Section 41(1)(b) CrPC checklist before arrest.",
      legal_issues: "Mandatory compliance of Section 41(1)(b) CrPC checklist before arrest.",
      arguments: "Arrests are made mechanically by police without satisfying statutory pre-conditions.",
      courtReasoning: "Arrest brings humiliation and curtails liberty. Police must serve Sec 41A notice instead of mechanical arrest.",
      court_reasoning: "Arrest brings humiliation and curtails liberty. Police must serve Sec 41A notice instead of mechanical arrest.",
      finalDecision: "Mandatory directions issued across India against automatic arrest.",
      final_decision: "Mandatory directions issued across India against automatic arrest.",
      citations: "Joginder Kumar v. State of UP (1994) 4 SCC 260."
    }
  },
  {
    id: "case_008",
    case_id: "PREC-008",
    title: "Phool Kumar vs. Delhi Administration",
    citation: "(1975) 1 SCC 797",
    court_id: 1,
    courtId: "court_001",
    courtName: "Supreme Court of India",
    court_name: "Supreme Court of India",
    year: 1975,
    location: "New Delhi",
    offence: "Meaning of 'Uses Deadly Weapon' in Section 397 IPC",
    legal_provisions: ["IPC Section 397", "IPC Section 392", "BNS Section 311"],
    legalProvisions: ["IPC Section 397", "IPC Section 392", "BNS Section 311"],
    weapon: "Knife / Gun",
    victim: "Victims of armed robbery",
    circumstances: "Interpretation of whether carrying and displaying a knife/firearm to intimidate victim without physically cutting or shooting constitutes 'use' under Section 397.",
    description: "Supreme Court held that the word 'uses' in Section 397 IPC does not require actual infliction of wound; if the offender carries and displays a deadly weapon to overawe the victim so as to facilitate the robbery, it satisfies the requirement of Section 397.",
    case_description: "Supreme Court held that the word 'uses' in Section 397 IPC does not require actual infliction of wound; if the offender carries and displays a deadly weapon to overawe the victim so as to facilitate the robbery, it satisfies the requirement of Section 397.",
    is_precedent: true,
    judgment: {
      judgment_id: 8,
      case_id: "PREC-008",
      facts: "Appellant and co-accused committed robbery at an urban residence. Appellant held a knife and threatened occupants while accomplices looted money and valuables.",
      case_facts: "Appellant and co-accused committed robbery at an urban residence. Appellant held a knife and threatened occupants while accomplices looted money and valuables.",
      legalIssues: "Interpretation of 'uses' in Section 397 IPC — whether physical injury is mandatory.",
      legal_issues: "Interpretation of 'uses' in Section 397 IPC — whether physical injury is mandatory.",
      arguments: "Appellant contended that 'use' means physical striking or inflicting injury with the weapon.",
      courtReasoning: "The Supreme Court clarified that 'uses' is not synonymous with 'wounds'. If a perpetrator carries a deadly weapon and displays it to intimidate, overawe, and terrorize the victim to enable the robbery without resistance, it constitutes 'use' under Section 397 IPC.",
      court_reasoning: "The Supreme Court clarified that 'uses' is not synonymous with 'wounds'. If a perpetrator carries a deadly weapon and displays it to intimidate, overawe, and terrorize the victim to enable the robbery without resistance, it constitutes 'use' under Section 397 IPC.",
      finalDecision: "Appeal dismissed. Mandatory minimum 7-year imprisonment confirmed.",
      final_decision: "Appeal dismissed. Mandatory minimum 7-year imprisonment confirmed.",
      citations: "Govind Mahto v. State of Bihar AIR 1958 Pat 378."
    }
  }
];

const demoPresets = [
  {
    id: "preset-robbery-knife",
    title: "Robbery at Jewellery Shop using Knife (Chennai)",
    court: "Madras High Court",
    location: "Chennai, Tamil Nadu",
    offence: "Robbery / Armed Dacoity",
    provisions: "IPC Section 392, Section 397 (BNS 309, 311)",
    description: "My client is accused of entering a jewellery retail store in T. Nagar, Chennai along with another person armed with a butcher knife. The shop owner was threatened and gold chains weighing 300g were taken. The defence argues the client did not wield the knife and was only outside on the motorcycle.",
    reason: "Finding precedents on Section 397 minimum sentence applicability for co-accused who did not wield the deadly weapon, and shop robbery judgments from Madras High Court."
  },
  {
    id: "preset-cyber-cheating",
    title: "Cyber Investment Fraud & Section 420 IPC / 318 BNS",
    court: "Karnataka High Court",
    location: "Bengaluru, Karnataka",
    offence: "Cheating & Cybercrime",
    provisions: "IPC Section 420, IT Act Section 66D, BNS 318(4)",
    description: "Accused allegedly solicited money from public promising 30% monthly trading returns through a fake digital web portal. Client was only an account holder whose bank account was used as a mule account. Seeking regular bail under Section 439 CrPC / BNSS 483.",
    reason: "Researching bail precedents in multi-victim online financial fraud where client claims no direct nexus with main mastermind."
  },
  {
    id: "preset-bail-guidelines",
    title: "Anticipatory Bail & Section 41A Notice Violation",
    court: "Supreme Court of India",
    location: "New Delhi",
    offence: "Bail / Unlawful Arrest",
    provisions: "CrPC Section 41A, Section 438, BNSS Section 35, Constitution Article 21",
    description: "Police arrested client for an offence with maximum punishment of 3 years without serving Section 41A CrPC notice and without recording specific reasons for necessity of arrest. Seeking urgent interim bail citing landmark Supreme Court guidelines.",
    reason: "Citing authoritative Supreme Court and High Court precedents on mandatory compliance of Section 41 CrPC checklist."
  }
];

module.exports = {
  courts,
  provisions,
  precedents,
  demoPresets
};
